### ISSUE TITLE
Open questions - register access

### ISSUE THREAD

**Issue by ramkumarkoppu** [ARMmbed/uvisor-lib#25] opened 2016-02-01 04:16 UTC
Hi,

Currently we are in the process of porting to new hardware and using FRDM-K64F as a experiment platform. My question is I did not find enough information about register access in the documentation page. how does uvisor either denies or control access to registers which control secure peripherals?
what happens to resources which are not defined in either non-sec and sec boxes ACL? do they default not accessible from non-sec box?

and also how uvisor handles bothe non-sec and secure interrupts?

**Comment by ciarmcom** [comment] 2016-02-01 08:40
ARM Internal Ref: IOTSFW-1932

**Comment by meriac** [comment] 2016-02-04 15:55
Closed, as issue is a duplicate of https://github.com/ARMmbed/uvisor/issues/38

**Closed by meriac** 2016-02-04 15:55 UTC
Labels: mirrored
